//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLogs
    {
        public string UserName { get; set; }
        public System.DateTime LoginDate { get; set; }
        public string ApplicationName { get; set; }
        public string IPAddress { get; set; }
    }
}
