//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ApplicationID { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationFullName { get; set; }
        public string ApplicationSlogan { get; set; }
        public string ApplicationPath { get; set; }
        public string ApplicationLogoName { get; set; }
        public string ApplicationPanelName { get; set; }
        public bool IsAuthenByCard { get; set; }
    }
}
