//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assets()
        {
            this.AssetDepreciations = new HashSet<AssetDepreciations>();
            this.AssetTransferDetails = new HashSet<AssetTransferDetails>();
        }
    
        public string AssetCode { get; set; }
        public string ParentAssetCode { get; set; }
        public string AssetName { get; set; }
        public string SerialNo { get; set; }
        public int BrandId { get; set; }
        public int AssetTypeId { get; set; }
        public string ModelNo { get; set; }
        public string Condition { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> AssetPartId { get; set; }
        public System.DateTime DateReceived { get; set; }
        public string ReceiveBy { get; set; }
        public string ReferenceNo { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.Guid> UserGUID { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string Location { get; set; }
        public byte[] Image { get; set; }
        public bool IsCalculateDP { get; set; }
        public Nullable<int> QtyYearDP { get; set; }
        public Nullable<System.DateTime> DateStartDP { get; set; }
        public string Remark { get; set; }
        public string CreateByUser { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ModifiedByUser { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual AssetBrands AssetBrands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetDepreciations> AssetDepreciations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetTransferDetails> AssetTransferDetails { get; set; }
        public virtual AssetTypes AssetTypes { get; set; }
        public virtual AssetStatuses AssetStatuses { get; set; }
    }
}
