//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTransferDetails
    {
        public int ItemNo { get; set; }
        public string AssetTransferNo { get; set; }
        public string AssetCode { get; set; }
        public string SerialNo { get; set; }
        public string Condition { get; set; }
        public string ParentAssetCode { get; set; }
        public string AssetPartName { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual AssetTransfers AssetTransfers { get; set; }
    }
}
