//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments
    {
        public int AttachmentId { get; set; }
        public int AttachmentNo { get; set; }
        public int TicketId { get; set; }
        public Nullable<int> CommentsId { get; set; }
        public byte[] AttachmentFile { get; set; }
        public string AttachmentMimeType { get; set; }
        public string AttachmentFileName { get; set; }
        public string AttachmentFileExtension { get; set; }
        public string AttachmentSize { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Comments Comments { get; set; }
    }
}
