//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int CommentsId { get; set; }
        public int ReTicketId { get; set; }
        public int StaffId { get; set; }
        public string CommentsName { get; set; }
        public System.DateTime CommentsDate { get; set; }
        public string CommentsStatus { get; set; }
        public string CommentsDetail { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
