//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configs
    {
        public int ConfigId { get; set; }
        public int ParentConfigId { get; set; }
        public string Name { get; set; }
        public Nullable<int> IntValue { get; set; }
        public Nullable<decimal> Numeric { get; set; }
        public string StringValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
    }
}
