//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses()
        {
            this.Trainings = new HashSet<Trainings>();
        }
    
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string CourseName_EN { get; set; }
        public int CourseTypeId { get; set; }
        public string Institution { get; set; }
        public string Objective { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByUser { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByUser { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public bool IsActive { get; set; }
        public string Instructor { get; set; }
        public decimal VariedCost { get; set; }
        public Nullable<decimal> HourPerHead { get; set; }
        public Nullable<bool> IsInternal { get; set; }
        public Nullable<bool> IsDSD { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainings> Trainings { get; set; }
    }
}
