//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentComments
    {
        public string LeaveRequestsId { get; set; }
        public int Time { get; set; }
        public string Username { get; set; }
        public int IsApproved { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
