//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int EducationId { get; set; }
        public string Username { get; set; }
        public Nullable<int> EducationLevelTypeId { get; set; }
        public string InstitutionName { get; set; }
        public string Province { get; set; }
        public Nullable<int> FromYear { get; set; }
        public Nullable<int> ToYear { get; set; }
        public string Major { get; set; }
        public Nullable<double> GPA { get; set; }
    }
}
