//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentLogs
    {
        public int ID { get; set; }
        public string NationalID { get; set; }
        public System.DateTime EmploymentStart { get; set; }
        public Nullable<System.DateTime> EmploymentResigned { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
