//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment
    {
        public int EmploymentId { get; set; }
        public string Username { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> DateStartEmployment { get; set; }
        public Nullable<System.DateTime> DateEndEmployment { get; set; }
        public string StartPosition { get; set; }
        public string EndPosition { get; set; }
        public string Responsibility { get; set; }
        public string ReasonForLeaving { get; set; }
    }
}
