//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraWorkingDays
    {
        public int ExtraWorkingDaysID { get; set; }
        public string UserName { get; set; }
        public int ShiftId { get; set; }
        public System.DateTime WorkDate { get; set; }
        public System.DateTime DateModified { get; set; }
        public string LastModifiedByUser { get; set; }
        public string FileImportName { get; set; }
        public string Comments { get; set; }
        public bool IsActive { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
