//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facitilities
    {
        public int TypeId { get; set; }
        public int UserID { get; set; }
        public string ModifiedByUser { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool Status { get; set; }
        public System.DateTime DateStart { get; set; }
    
        public virtual MasterTypes MasterTypes { get; set; }
    }
}
