//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grants
    {
        public int GrantId { get; set; }
        public int CompanyCode { get; set; }
        public int TypeId { get; set; }
        public int SubTypeId { get; set; }
        public int MinAge { get; set; }
        public int MaxAge { get; set; }
        public Nullable<int> MinRank { get; set; }
        public Nullable<int> MaxRank { get; set; }
        public Nullable<decimal> Value1 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public bool RequirePostProbation { get; set; }
        public int GrantTypeId { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
    }
}
