//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holidays
    {
        public int HolidayGroupId { get; set; }
        public System.DateTime DateHoliday { get; set; }
        public string HolidayName { get; set; }
        public bool IsActive { get; set; }
        public string CreatedByUser { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ModifiedByUser { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual MasterTypes MasterTypes { get; set; }
    }
}
