//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApprovals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveApprovals()
        {
            this.LeaveRequests = new HashSet<LeaveRequests>();
        }
    
        public int LeaveRequestId { get; set; }
        public string ApprovedByUsername { get; set; }
        public string ApprovedBy { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public System.DateTime DateApproved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRequests> LeaveRequests { get; set; }
    }
}
