//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveSummary
    {
        public string Username { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public double TotalShiftEntryCost { get; set; }
        public double TotalWorkHours { get; set; }
        public int AbsenceCount { get; set; }
        public int LateCount { get; set; }
        public double LateHours { get; set; }
        public int EarlyFinishWorkCount { get; set; }
        public double EarlyFinishWorkHours { get; set; }
        public int NoTimeInCount { get; set; }
        public int NoTimeOutCount { get; set; }
        public int BusinessLeaveCount { get; set; }
        public double BusinessLeaveHours { get; set; }
        public int HolidayLeaveCount { get; set; }
        public double HolidayLeaveHours { get; set; }
        public int SickLeaveCount { get; set; }
        public double SickLeaveHours { get; set; }
        public int MaternityleaveCount { get; set; }
        public double MaternityleaveHours { get; set; }
        public double IncentiveCost { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
