//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveAttachments
    {
        public int LeaveRequestId { get; set; }
        public int LeaveAttachmentsNo { get; set; }
        public byte[] AttachmentFile { get; set; }
        public string AttachmentFilename { get; set; }
        public string AttachmentType { get; set; }
    
        public virtual LeaveRequests LeaveRequests { get; set; }
    }
}
