//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveRequests()
        {
            this.LeaveAttachments = new HashSet<LeaveAttachments>();
        }
    
        public int LeaveRequestId { get; set; }
        public string Username { get; set; }
        public int EventId { get; set; }
        public Nullable<System.DateTime> DateNightShiftEffective { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public Nullable<System.DateTime> DateChangeFrom { get; set; }
        public Nullable<System.DateTime> DateChangeTo { get; set; }
        public int TotalDays { get; set; }
        public double TotalHours { get; set; }
        public double PayRate { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }
        public string ApprovedByUsername { get; set; }
        public string CreatedByUsername { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string CurrentApprovalUsername { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<bool> HasAttachment { get; set; }
        public Nullable<bool> IsOverDue { get; set; }
    
        public virtual LeaveApprovals LeaveApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveAttachments> LeaveAttachments { get; set; }
        public virtual MasterTypes MasterTypes { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
