//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterOfGuaruntees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LetterOfGuaruntees()
        {
            this.LetterOfGuarunteeDetails = new HashSet<LetterOfGuarunteeDetails>();
        }
    
        public string Username { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> CutMoneyType { get; set; }
        public string BondsMan { get; set; }
        public string Remark { get; set; }
        public double MoneyGuaruntee { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public string Belong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterOfGuarunteeDetails> LetterOfGuarunteeDetails { get; set; }
        public virtual MasterTypes MasterTypes { get; set; }
        public virtual MasterTypes MasterTypes1 { get; set; }
    }
}
