//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lockers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lockers()
        {
            this.LockerHistories = new HashSet<LockerHistories>();
        }
    
        public int LockerID { get; set; }
        public string LockerCode { get; set; }
        public int LockerLocationID { get; set; }
        public string OwnerUser { get; set; }
        public bool IsUsed { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public string KeyID { get; set; }
        public Nullable<byte> MasterKey { get; set; }
        public Nullable<byte> KeyTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LockerHistories> LockerHistories { get; set; }
        public virtual LockerLocations LockerLocations { get; set; }
    }
}
