//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockerHistories
    {
        public int HistoryID { get; set; }
        public int LockerID { get; set; }
        public string OwnerUser { get; set; }
        public Nullable<int> ChangeReasonID { get; set; }
        public Nullable<int> CancelReasonID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string CreateBy { get; set; }
        public string EndBy { get; set; }
    
        public virtual Lockers Lockers { get; set; }
    }
}
