//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementLogs
    {
        public int MovementLogId { get; set; }
        public int MovementType { get; set; }
        public string MovementTypeName { get; set; }
        public Nullable<int> QuotaType { get; set; }
        public string QuotaTypeName { get; set; }
        public System.DateTime DateEffective { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> RankTypeId { get; set; }
        public string RankTypeName { get; set; }
        public Nullable<System.Guid> PositionCode { get; set; }
        public string PositionName { get; set; }
        public string DivisionCode { get; set; }
        public string DivisionName { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public Nullable<byte> StatusCode { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> EmployeeTypeCode { get; set; }
        public string EmployeeTypeName { get; set; }
        public Nullable<int> OldRankTypeId { get; set; }
        public string OldRankTypeName { get; set; }
        public Nullable<System.Guid> OldPositionCode { get; set; }
        public string OldPositionName { get; set; }
        public string OldDepartmentCode { get; set; }
        public string OldDepartmentName { get; set; }
        public string OldDivisionCode { get; set; }
        public string OldDivisionName { get; set; }
        public Nullable<byte> OldStatusCode { get; set; }
        public string OldStatusName { get; set; }
        public Nullable<int> OldEmployeeTypeCode { get; set; }
        public string OldEmployeeTypeName { get; set; }
        public Nullable<int> OldCompanyCode { get; set; }
        public string OldCompanyName { get; set; }
        public Nullable<int> RefLogId { get; set; }
        public Nullable<int> ParentMovementLogId { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TerminationTypeId { get; set; }
        public Nullable<int> ResignTypeId { get; set; }
    
        public virtual MasterTypes MasterTypes { get; set; }
    }
}
