//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTApprovals
    {
        public int OTRequestId { get; set; }
        public string ApprovedByUsername { get; set; }
        public string ApprovedBy { get; set; }
        public string Reason { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime DateApproved { get; set; }
    
        public virtual OTRequests OTRequests { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
