//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentInfos
    {
        public int ParentInfoId { get; set; }
        public string Username { get; set; }
        public int ParentTitleCode { get; set; }
        public string ParentFirstname { get; set; }
        public string ParentLastname { get; set; }
        public string ParentVocation { get; set; }
        public string ParentNationalId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual MasterTypes MasterTypes { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
