//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictures
    {
        public int PicId { get; set; }
        public int ReTicketId { get; set; }
        public string PicName { get; set; }
        public string PicType { get; set; }
        public byte[] PicImg { get; set; }
    
        public virtual Requests Requests { get; set; }
    }
}
