//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidentFundPlan
    {
        public int ProvidentFundTypeId { get; set; }
        public int ProvidentFundPlanId { get; set; }
        public string ProvidentFundPlanName { get; set; }
        public bool IsActive { get; set; }
    }
}
