//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidentFunds
    {
        public int ProvidentFundId { get; set; }
        public int ProvidentFundRateId { get; set; }
        public int ProvidentFundPercentageId { get; set; }
        public int ProvidentFundTypeId { get; set; }
        public Nullable<int> ProvidentFundPlanId { get; set; }
        public string Username { get; set; }
        public double PercentageEmp { get; set; }
        public int ProvidentFundStatus { get; set; }
        public Nullable<System.DateTime> ProvidentFundDateStart { get; set; }
        public Nullable<System.DateTime> ProvidentFundDateResigned { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateBankSumbit { get; set; }
        public Nullable<System.DateTime> DateChequeReceipt { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateFundTransactionCreated { get; set; }
    
        public virtual MasterTypes MasterTypes { get; set; }
        public virtual ProvidentFundPercentages ProvidentFundPercentages { get; set; }
        public virtual ProvidentFundRates ProvidentFundRates { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
