//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Comments = new HashSet<Comments>();
            this.Pictures = new HashSet<Pictures>();
        }
        [Required]
        public int ReTicketId { get; set; }
        [Required]
        public int TypeRequestsId { get; set; }
        [Required]
        public int StaffId { get; set; }
        [Required]
        public int StatusId { get; set; }
        [Required]
        public string ReTopicName { get; set; }
        [Required]
        public string ReCustomerName { get; set; }
        [StringLength(maximumLength:10,ErrorMessage = "โปรป้อนให้ครบ 10หลัก", MinimumLength = 10)]
        public string ReCustomerTel { get; set; }
        [Required]
        [EmailAddress]
        public string ReEmail { get; set; }
        [Required]
        [MaxLength(1000)]
        public string ReDetail { get; set; }
        [Required]
        public System.DateTime ReDateIn { get; set; }
        public Nullable<System.DateTime> ReDateOut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pictures> Pictures { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual TypeRequests TypeRequests { get; set; }
    }
}
