//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Attachments = new HashSet<Attachments>();
            this.Comments = new HashSet<Comments>();
        }
    
        public int TicketId { get; set; }
        public int RequestTypeId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public int StatusId { get; set; }
        public string TopicName { get; set; }
        public string CustomerName { get; set; }
        public string TelephoneNumber { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CurrentStaffId { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachments> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual RequestType RequestType { get; set; }
    }
}
