//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shifts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shifts()
        {
            this.PeriodDetails = new HashSet<PeriodDetails>();
            this.UserInShifts = new HashSet<UserInShifts>();
        }
    
        public int ShiftId { get; set; }
        public string ShiftName { get; set; }
        public string ShiftName_EN { get; set; }
        public bool HasWorkTime { get; set; }
        public Nullable<int> StampDateTypeFrom { get; set; }
        public Nullable<int> StampDateTypeTo { get; set; }
        public Nullable<System.TimeSpan> StampFrom { get; set; }
        public Nullable<System.TimeSpan> StampTo { get; set; }
        public Nullable<int> WorkDateTypeIn { get; set; }
        public Nullable<int> WorkDateTypeOut { get; set; }
        public Nullable<System.TimeSpan> WorkTimeIn { get; set; }
        public Nullable<System.TimeSpan> WorkTimeOut { get; set; }
        public Nullable<int> BreakDateTypeIn { get; set; }
        public Nullable<int> BreakDateTypeOut { get; set; }
        public Nullable<System.TimeSpan> BreakTimeIn { get; set; }
        public Nullable<System.TimeSpan> BreakTimeOut { get; set; }
        public double PayRate { get; set; }
        public double ShiftEntryCost { get; set; }
        public bool IsNightShift { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedByUsername { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedByUsername { get; set; }
        public bool IsFreedom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriodDetails> PeriodDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInShifts> UserInShifts { get; set; }
    }
}
