//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeStamps
    {
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public string Username { get; set; }
        public System.TimeSpan Time { get; set; }
        public Nullable<bool> IsTransfer { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
