//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainings
    {
        public int TrainingId { get; set; }
        public string Username { get; set; }
        public int CourseId { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
