//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInGroupMeetings
    {
        public int UserInGruopMeetingId { get; set; }
        public string Username { get; set; }
        public Nullable<int> MeetingGroupId { get; set; }
    
        public virtual MeetingGroups MeetingGroups { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
