//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInPeriods
    {
        public string Username { get; set; }
        public int PeriodId { get; set; }
        public System.DateTime DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedByUsername { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedByUsername { get; set; }
    
        public virtual Periods Periods { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
