//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPrivateInfo
    {
        public string Username { get; set; }
        public string NationalID { get; set; }
        public Nullable<System.DateTime> DateNationalIdCardExpire { get; set; }
        public string SocialSecurityID { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<int> Bank { get; set; }
        public System.DateTime DateModified { get; set; }
        public string LastModifiedByUser { get; set; }
        public string Salary { get; set; }
        public string EvidenceOfRegistrationSSO { get; set; }
        public Nullable<short> StatusChildSSO { get; set; }
        public string TypeCardSSO { get; set; }
        public string NationalitySSO { get; set; }
        public string NumberOfChildSSO { get; set; }
        public string TypeOfEmploymentSSO { get; set; }
        public string HostpitalCodeSSO { get; set; }
        public Nullable<System.DateTime> DateReceivedSSO { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
