//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInShifts
    {
        public string Username { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<System.TimeSpan> StampIn { get; set; }
        public Nullable<System.TimeSpan> StampOut { get; set; }
        public Nullable<System.DateTime> TrueStampInDate { get; set; }
        public Nullable<System.DateTime> TrueStampOutDate { get; set; }
        public Nullable<int> LeaveRequestId1 { get; set; }
        public Nullable<int> LeaveRequestId2 { get; set; }
        public Nullable<int> LeaveRequestId3 { get; set; }
        public int EventId { get; set; }
        public string Remark { get; set; }
        public double ShiftEntryCost { get; set; }
        public Nullable<double> ShiftEntryCostSP { get; set; }
        public Nullable<double> WorkHours { get; set; }
        public double Late { get; set; }
        public double Early { get; set; }
        public double Absence { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<decimal> SickLeave { get; set; }
        public Nullable<decimal> OrdianLeave { get; set; }
        public Nullable<decimal> HolidayLeave { get; set; }
        public Nullable<decimal> BussinessLeave { get; set; }
        public Nullable<decimal> DeliverLeave { get; set; }
        public Nullable<decimal> CompassionLeave { get; set; }
        public Nullable<decimal> HasDocumentSickLeave { get; set; }
        public Nullable<decimal> BeyondSickLeave { get; set; }
        public Nullable<decimal> BeyondBussinessLeave { get; set; }
        public Nullable<bool> IsFix { get; set; }
    
        public virtual MasterTypes MasterTypes { get; set; }
        public virtual Shifts Shifts { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
