//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.Addresses = new HashSet<Addresses>();
            this.Attachments = new HashSet<Attachments>();
            this.DocumentComments = new HashSet<DocumentComments>();
            this.ExtraWorkingDays = new HashSet<ExtraWorkingDays>();
            this.Incentive = new HashSet<Incentive>();
            this.LeaveRequests = new HashSet<LeaveRequests>();
            this.LeaveSummary = new HashSet<LeaveSummary>();
            this.MeetingDetails = new HashSet<MeetingDetails>();
            this.OTApprovals = new HashSet<OTApprovals>();
            this.OTRequests = new HashSet<OTRequests>();
            this.ParentInfos = new HashSet<ParentInfos>();
            this.ProvidentFunds = new HashSet<ProvidentFunds>();
            this.PRPOUserStats = new HashSet<PRPOUserStats>();
            this.TimeStamps = new HashSet<TimeStamps>();
            this.Trainings = new HashSet<Trainings>();
            this.UserLeaveDays = new HashSet<UserLeaveDays>();
            this.UserInGroupMeetings = new HashSet<UserInGroupMeetings>();
            this.UserInPeriods = new HashSet<UserInPeriods>();
            this.UserInShifts = new HashSet<UserInShifts>();
        }
    
        public Nullable<short> OrgLevel { get; set; }
        public Nullable<short> OrgLevel2 { get; set; }
        public Nullable<int> CardNo { get; set; }
        public string BarcodeNo { get; set; }
        public int CompanyCode { get; set; }
        public int UserID { get; set; }
        public string Username { get; set; }
        public byte StatusCode { get; set; }
        public int EmployeeType { get; set; }
        public int TitleCode { get; set; }
        public string Firstname { get; set; }
        public string Firstname_EN { get; set; }
        public string Lastname { get; set; }
        public string Lastname_EN { get; set; }
        public string Fullname { get; set; }
        public string Fullname_EN { get; set; }
        public string Nickname { get; set; }
        public string Nickname_EN { get; set; }
        public int GenderCode { get; set; }
        public Nullable<int> MaritalStatusCode { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> ELCode { get; set; }
        public Nullable<System.DateTime> DateEmployed { get; set; }
        public string Privilege { get; set; }
        public Nullable<byte> Rank { get; set; }
        public int RankTypeNo { get; set; }
        public Nullable<bool> HasPicture { get; set; }
        public byte[] Picture { get; set; }
        public System.Guid PositionCode { get; set; }
        public string DivisionCode { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<short> ExtensionNo { get; set; }
        public string TelNo { get; set; }
        public string ManagerUsername { get; set; }
        public string ManagerUsername2 { get; set; }
        public string M2Username { get; set; }
        public string M3Username { get; set; }
        public string E1Username { get; set; }
        public string E2Username { get; set; }
        public string E3Username { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
        public string LastModifiedByUser { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public Nullable<int> TerminationTypeId { get; set; }
        public Nullable<int> ResignTypeId { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string EmsContactName { get; set; }
        public string EmsContactLastName { get; set; }
        public string EmsContactTelNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Addresses> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachments> Attachments { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Divisions Divisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentComments> DocumentComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraWorkingDays> ExtraWorkingDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incentive> Incentive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRequests> LeaveRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveSummary> LeaveSummary { get; set; }
        public virtual MasterTypes MasterTypes { get; set; }
        public virtual MasterTypes MasterTypes1 { get; set; }
        public virtual MasterTypes MasterTypes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingDetails> MeetingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTApprovals> OTApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTRequests> OTRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParentInfos> ParentInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvidentFunds> ProvidentFunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRPOUserStats> PRPOUserStats { get; set; }
        public virtual Statuses Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeStamps> TimeStamps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainings> Trainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLeaveDays> UserLeaveDays { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
        public virtual UserInfo UserInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInGroupMeetings> UserInGroupMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInPeriods> UserInPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInShifts> UserInShifts { get; set; }
        public virtual UserPrivateInfo UserPrivateInfo { get; set; }
    }
}
