//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAddresses
    {
        public int AddressId { get; set; }
        public string Username { get; set; }
        public Nullable<int> AddressType { get; set; }
        public string AddressPart1 { get; set; }
        public string SubDistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public bool IsDefault { get; set; }
        public string TypeName { get; set; }
        public string TypeName_EN { get; set; }
    }
}
