//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAssetTypes
    {
        public int AssetTypeId { get; set; }
        public string AssetTypeCode { get; set; }
        public string AssetTypeName { get; set; }
        public Nullable<int> ParentAssetTypeId { get; set; }
        public string AssetGroupName { get; set; }
        public Nullable<bool> IsPCSet { get; set; }
        public Nullable<bool> ITAssets { get; set; }
    }
}
