//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAssetMaxTransaction
    {
        public System.DateTime DateTransfer { get; set; }
        public string AssetTransferNo { get; set; }
        public string TransferTypeName { get; set; }
        public string FromUser { get; set; }
        public string FromDepartmentName { get; set; }
        public string ToUser { get; set; }
        public string ToDepartmentName { get; set; }
        public string ReceiveBy { get; set; }
        public string ReasonForTransfer { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public string Remark { get; set; }
        public string AssetCode { get; set; }
        public int TransferTypeId { get; set; }
        public Nullable<System.DateTime> DateDueReturn { get; set; }
        public string AssetName { get; set; }
    }
}
