//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAssetChanges
    {
        public Nullable<System.DateTime> DateTransfer { get; set; }
        public string AssetTransferNo { get; set; }
        public Nullable<System.Guid> ToUserGUID { get; set; }
        public string ToUser { get; set; }
        public string ToDepartmentCode { get; set; }
        public string ToDepartmentName { get; set; }
        public string ReasonForTransfer { get; set; }
        public string Remark { get; set; }
        public string AssetCode { get; set; }
        public string AssetName { get; set; }
        public string SerialNo { get; set; }
        public string oldAssetCode { get; set; }
        public string oldAssetName { get; set; }
        public string oldSerialNo { get; set; }
        public string ParentAssetCode { get; set; }
        public string ChangeName { get; set; }
    }
}
