//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAssetTransfers
    {
        public string TransferTypeName { get; set; }
        public string AssetTransferNo { get; set; }
        public System.DateTime DateTransfer { get; set; }
        public Nullable<System.DateTime> DateDueReturn { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public int TransferTypeId { get; set; }
        public string ReceiveBy { get; set; }
        public string SendBy { get; set; }
        public Nullable<System.Guid> FromUserGUID { get; set; }
        public string FromUser { get; set; }
        public Nullable<System.Guid> ToUserGUID { get; set; }
        public string ToUser { get; set; }
        public string FromDepartmentName { get; set; }
        public string ToDepartmentName { get; set; }
        public string ReasonForTransfer { get; set; }
        public bool IsCancel { get; set; }
        public string ReasonForCancel { get; set; }
        public string RefAssetTransferNo { get; set; }
        public string Remark { get; set; }
        public string CreateByUser { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ModifiedByUser { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ToDepartmentCode { get; set; }
        public string FromDepartmentCode { get; set; }
        public string IsCancelName { get; set; }
    }
}
