//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAssetUserInfo
    {
        public System.Guid UserGUID { get; set; }
        public string Username { get; set; }
        public int StatusCode { get; set; }
        public int TitleCode { get; set; }
        public string TitleName { get; set; }
        public string Firstname { get; set; }
        public string Firstname_EN { get; set; }
        public string Lastname { get; set; }
        public string Lastname_EN { get; set; }
        public string Fullname { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public int UserID { get; set; }
        public string DivisionCode { get; set; }
        public string DivisionName { get; set; }
        public Nullable<int> OrgLevel { get; set; }
        public string PositionName { get; set; }
    }
}
