//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAssetDepreciations
    {
        public string AssetName { get; set; }
        public System.DateTime DateDepreciation { get; set; }
        public string AssetCode { get; set; }
        public decimal DepreciationValue { get; set; }
        public System.DateTime MonthDP { get; set; }
    }
}
