//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAssetItemDetails
    {
        public string AssetCode { get; set; }
        public string ParentAssetCode { get; set; }
        public string AssetName { get; set; }
        public string SerialNo { get; set; }
        public string ModelNo { get; set; }
        public string BrandName { get; set; }
        public string AssetTypeName { get; set; }
    }
}
