//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCardHistories
    {
        public int HistoryID { get; set; }
        public int CardID { get; set; }
        public string CardCode { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Fullname { get; set; }
        public string DivisionName { get; set; }
        public string DepartmentName { get; set; }
        public string PositionName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CardType { get; set; }
        public Nullable<int> CancelReasonID { get; set; }
        public string TypeName { get; set; }
        public string Remark { get; set; }
        public string OwnerUser { get; set; }
        public string FullNameSub { get; set; }
        public string ModifiedBy { get; set; }
    }
}
