//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCards
    {
        public int CardID { get; set; }
        public string CardCode { get; set; }
        public string OwnerUser { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Fullname { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsUsed { get; set; }
        public bool IsActive { get; set; }
        public bool IsBreak { get; set; }
        public Nullable<System.DateTime> DateEmployed { get; set; }
        public string CardType { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public string ShowCard { get; set; }
        public Nullable<int> CancelReasonID { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> HistoryDateCreate { get; set; }
        public string HistoryFullname { get; set; }
        public string LastOwnerUser { get; set; }
        public string LastFullname { get; set; }
        public Nullable<int> LastUserID { get; set; }
        public string DivisionName { get; set; }
        public string DepartmentName { get; set; }
        public string PositionName { get; set; }
        public string TypeName { get; set; }
    }
}
