//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCourses
    {
        public int TrainingId { get; set; }
        public string Username { get; set; }
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string CourseName_EN { get; set; }
        public int CourseTypeId { get; set; }
        public string Institution { get; set; }
        public string Objective { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string Location { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByUser { get; set; }
        public string ModifiedByUser { get; set; }
        public bool IsActive { get; set; }
        public string TypeName { get; set; }
        public string Fullname { get; set; }
        public string Fullname_EN { get; set; }
        public string RankName { get; set; }
        public string PositionName { get; set; }
        public string DepartmentName { get; set; }
        public string DivisionName { get; set; }
        public string TitleName { get; set; }
        public string Gender { get; set; }
        public int GenderCode { get; set; }
    }
}
