//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDatadict
    {
        public string Table { get; set; }
        public string Attribute { get; set; }
        public string Type { get; set; }
        public string Allow_Nulls_ { get; set; }
        public string PKey_ { get; set; }
        public string FKey_ { get; set; }
        public string Ref_Table { get; set; }
        public string Descriptions { get; set; }
        public string name { get; set; }
        public byte xtype { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<short> xusertype { get; set; }
        public short length { get; set; }
        public byte xprec { get; set; }
        public byte xscale { get; set; }
        public int tdefault { get; set; }
        public int domain { get; set; }
        public Nullable<short> uid { get; set; }
        public Nullable<short> reserved { get; set; }
        public Nullable<int> collationid { get; set; }
        public Nullable<short> usertype { get; set; }
        public bool variable { get; set; }
        public Nullable<bool> allownulls { get; set; }
        public byte Expr1 { get; set; }
        public string printfmt { get; set; }
        public Nullable<short> prec { get; set; }
        public Nullable<byte> scale { get; set; }
        public string collation { get; set; }
        public string Expr2 { get; set; }
        public int id { get; set; }
        public byte Expr3 { get; set; }
        public Nullable<byte> typestat { get; set; }
        public Nullable<short> Expr4 { get; set; }
        public short Expr5 { get; set; }
        public byte Expr6 { get; set; }
        public byte Expr7 { get; set; }
        public Nullable<short> colid { get; set; }
        public Nullable<short> xoffset { get; set; }
        public Nullable<byte> bitpos { get; set; }
        public Nullable<byte> Expr8 { get; set; }
        public Nullable<short> colstat { get; set; }
        public int cdefault { get; set; }
        public int Expr9 { get; set; }
        public Nullable<short> number { get; set; }
        public Nullable<short> colorder { get; set; }
        public byte[] autoval { get; set; }
        public Nullable<short> offset { get; set; }
        public Nullable<int> Expr10 { get; set; }
        public Nullable<int> language { get; set; }
        public Nullable<byte> Expr11 { get; set; }
        public byte Expr12 { get; set; }
        public Nullable<short> Expr13 { get; set; }
        public string Expr14 { get; set; }
        public Nullable<short> Expr15 { get; set; }
        public Nullable<int> Expr16 { get; set; }
        public Nullable<int> iscomputed { get; set; }
        public Nullable<int> isoutparam { get; set; }
        public Nullable<int> isnullable { get; set; }
        public string Expr17 { get; set; }
        public byte[] tdscollation { get; set; }
    }
}
