//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDepartment
    {
        public string DivisionCode { get; set; }
        public string DivisionName { get; set; }
        public string Departmentcode { get; set; }
        public string DepartmentName { get; set; }
        public bool IsActive { get; set; }
    }
}
