//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFoodCouponCompany
    {
        public string CouponId { get; set; }
        public int CouponTypeId { get; set; }
        public string Username { get; set; }
        public System.DateTime DateCoupon { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CompanyCode { get; set; }
        public string TypeName { get; set; }
    }
}
