//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLeacePrivilegeConfig
    {
        public string TypeName { get; set; }
        public int LeaveDays { get; set; }
        public int MinimumYear { get; set; }
        public int MaximumYear { get; set; }
        public int MinimumRank { get; set; }
        public int MaximumRank { get; set; }
        public int LeaveTypeId { get; set; }
        public bool Status { get; set; }
        public string MinRank { get; set; }
        public string MaxRank { get; set; }
        public int CompanyCode { get; set; }
        public string CompanyName { get; set; }
    }
}
