//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLockerLites
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Fullname { get; set; }
        public string DivisionCode { get; set; }
        public string DepartmentCode { get; set; }
        public byte StatusCode { get; set; }
        public string LockerCode { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string FullnameWithLockerCode { get; set; }
    }
}
