//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLockAndApproveUser
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Fullname { get; set; }
        public string DivisionName { get; set; }
        public string DepartmentCode { get; set; }
        public string PositionName { get; set; }
        public string DivisionCode { get; set; }
        public string M3Username { get; set; }
        public string M2Username { get; set; }
        public string E1Username { get; set; }
        public string E2Username { get; set; }
        public string E3Username { get; set; }
        public byte RankTypeNo { get; set; }
        public string DepartmentName { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLockedOut { get; set; }
        public byte StatusCode { get; set; }
        public string StatusName { get; set; }
        public string RankName { get; set; }
    }
}
