//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTimeStamps
    {
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public string Username { get; set; }
        public Nullable<bool> IsTransfer { get; set; }
        public Nullable<System.TimeSpan> Time1 { get; set; }
        public Nullable<System.TimeSpan> Time2 { get; set; }
        public Nullable<System.TimeSpan> Time3 { get; set; }
        public Nullable<System.TimeSpan> Time4 { get; set; }
        public Nullable<System.TimeSpan> Time5 { get; set; }
        public Nullable<System.TimeSpan> Time6 { get; set; }
        public Nullable<System.TimeSpan> Time7 { get; set; }
        public Nullable<System.TimeSpan> Time8 { get; set; }
    }
}
