//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserLeaveDays
    {
        public string Username { get; set; }
        public string Fullname { get; set; }
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public int Year { get; set; }
        public int Days { get; set; }
        public int Hours { get; set; }
        public int UsedDays { get; set; }
        public double UsedHours { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedByUsername { get; set; }
        public string TelNo { get; set; }
        public Nullable<int> LeftDays { get; set; }
        public double LeftHours { get; set; }
    }
}
