//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUsersInRoles
    {
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public string RoleName { get; set; }
        public string UserName { get; set; }
        public string BarcodeNo { get; set; }
        public string Fullname { get; set; }
    }
}
