//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserInfo2
    {
        public Nullable<short> OrgLevel { get; set; }
        public Nullable<short> OrgLevel2 { get; set; }
        public Nullable<int> CardNo { get; set; }
        public int CompanyCode { get; set; }
        public System.Guid UserGUID { get; set; }
        public int UserID { get; set; }
        public string Username { get; set; }
        public byte StatusCode { get; set; }
        public string StatusName { get; set; }
        public string TitleName { get; set; }
        public string Firstname { get; set; }
        public string Firstname_EN { get; set; }
        public string Lastname { get; set; }
        public string Lastname_EN { get; set; }
        public string Fullname { get; set; }
        public string Fullname_EN { get; set; }
        public string Nickname { get; set; }
        public string Nickname_EN { get; set; }
        public int GenderCode { get; set; }
        public string Gender { get; set; }
        public Nullable<int> MaritalStatusCode { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> ELCode { get; set; }
        public Nullable<System.DateTime> DateEmployed { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public string Privilege { get; set; }
        public Nullable<byte> Rank { get; set; }
        public int RankTypeNo { get; set; }
        public string RankName { get; set; }
        public byte[] Picture { get; set; }
        public byte[] Thumbnail { get; set; }
        public System.Guid PositionCode { get; set; }
        public string PositionName { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string DivisionCode { get; set; }
        public string DivisionName { get; set; }
        public Nullable<short> ExtensionNo { get; set; }
        public string TelNo { get; set; }
        public string ManagerUsername { get; set; }
        public string ManagerUsername2 { get; set; }
        public string M2Username { get; set; }
        public string M3Username { get; set; }
        public string E1Username { get; set; }
        public string E2Username { get; set; }
        public string E3Username { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public string LastModifiedByUser { get; set; }
        public string BarcodeNo { get; set; }
        public int TitleCode { get; set; }
        public int EmployeeType { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string EmsContactName { get; set; }
        public string EmsContactLastName { get; set; }
        public string EmsContactTelNo { get; set; }
        public string PositionName_EN { get; set; }
    }
}
