//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMforCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WelfareHistories
    {
        public int WelfareHistoryId { get; set; }
        public int WelfareTypeId { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> DateTrans { get; set; }
        public Nullable<int> Relationship { get; set; }
        public string Person1 { get; set; }
        public string Person2 { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string Value { get; set; }
        public string Remark { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public string WelfareTypeName { get; set; }
    }
}
